name: Publish package

on:
  push:
    paths:
      - nodejs/nodeDeb.sh

jobs:
  build-nodejs-deb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt update && sudo apt-get install build-essential dpkg

    - name: Build Deb File
      run: |
        bash nodejs/nodeDeb.sh

    - name: Extract Node.js Version
      id: extract_version
      run: echo "NODE_VERSION=$(grep -oP "version='\K[^']+" nodejs/nodeDeb.sh)" >> $GITHUB_ENV

    - name: Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with: 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.NODE_VERSION }}"
        prerelease: false
        title: "Node.js ${{ env.NODE_VERSION }} LTS Build"
        files: |
          *.deb
